In [1]:
import os
import re
import json
import tqdm
import numpy as np
import ray
import openai
import tiktoken

import time
import ast

openai.api_key = "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"

In [51]:
class RedundantParenthesesRemover(ast.NodeTransformer):
    def visit_Expr(self, node):
        self.generic_visit(node)
        if isinstance(node.value, ast.BinOp):
            return node.value
        return node

def remove_redundant_parentheses(expression):
    # Parse the expression
    parsed_expression = ast.parse(expression)

    # Remove redundant parentheses
    transformer = RedundantParenthesesRemover()
    transformed_expression = transformer.visit(parsed_expression)

    # Convert the transformed expression back to a string
    simplified_expression = ast.unparse(transformed_expression)

    return simplified_expression
    
def divide(a, b):
    return f"({a} / {b})"

def subtract(a, b):
    return f"({a} - {b})"

def multiply(a, b):
    return f"({a} * {b})"

def add(a, b):
    return f"({a} + {b})"

def exp(a, b):
    return f"({a} ** {b})"

def greater(a, b):
    return f"({a} > {b})"

def translate_expr(expr):
    if "table" in expr:
        return expr
    
    # replace const_m1
    expr = re.sub(r'const_m1', r'-1', expr)

    # change % to / 100
    expr = re.sub(r'([0-9]*\.?[0-9]+)%', r'divide(\1 , 100)', expr)
    
    expr = re.sub(r'const_([0-9]*\.?[0-9]+)', r'\1', expr)
    try:
        new_expr = eval(expr)
        new_expr = remove_redundant_parentheses(new_expr)
    except Exception as e:
        print(e, expr)
        new_expr = expr
    
    return new_expr

def convert_to_markdown(data):
    markdown = "|"
    
    # Add table headers
    for header in data[0]:
        markdown += header + "|"
    markdown += "\n|"
    
    # Add table header separators
    for _ in data[0]:
        markdown += "---|"
    markdown += "\n"
    
    # Add table rows
    for row in data[1:]:
        markdown += "|"
        for cell in row:
            markdown += cell + "|"
        markdown += "\n"
        
    return markdown

def extract_answer(response):
    # extract content inside Calculate()
    matches = re.findall(r"Calculate\(([\(\)0-9 ><,\.\/\+\-\*]*)\)", response)
    if len(matches) == 0:
        if "Yes" in response:
            return "Yes"
        elif "No" in response:
            return "No"
        else:
            return ""
    else:
        output = matches[0].replace(",", "")
        return output
    
def if_exec_correct(t_prog, g_prog):
    try:
        t_exec = eval(t_prog)

        if type(t_exec) == bool and g_prog in ["Yes", "No"]:
            t_exec = "Yes" if t_exec else "No"

            if t_exec == g_prog:
                return True
            
        g_exec = eval(g_prog)

        if t_exec == g_exec:
            return True
        elif t_exec * 100 == g_exec:
            return True
        elif t_exec * 100 == -g_exec:
            return True
        elif t_exec == g_exec * 100:
            return True
        elif t_exec == -g_exec * 100:
            return True
        elif t_exec * 1000000 == g_exec:
            return True
        elif t_exec * 1000000 == -g_exec:
            return True
        elif t_exec == g_exec * 1000000:
            return True
        elif t_exec == -g_exec * 1000000:
            return True
        elif t_exec == -g_exec:
            return True
    except:
        return False

    return False

In [3]:
tokenizer = tiktoken.encoding_for_model("davinci")

In [4]:
system_prompt = (
                "You need to answer the user's question in the ### Question ### section.\n" \
                "You need to provide the answer in the format 'Calculate(a + b)', where the expression needs to be python excutable." \
                # "You can calculate the average of a column by using the function 'Average(table_column_name)'.\n" \
                # "Similarly, you can calculate the sum, the maximum, the minimum, the count of a column by using the functions "\
                # "'Sum(table_column_name)', 'Max(table_column_name)', 'Min(table_column_name)', 'Count(table_column_name)' respectively.\n" \
                # "You only use the table's column name inside those operations\n" \
                "For example, if the question is 'What is the sum of 1 + 2?', you need to answer 'Calc(1 + 2)'." \
                "if the question is 'Is 123 greater than 231?', you need to answer 'Calc(123 > 231)'." \
                # "|Age|\n|---|\n|12|\n|15|\n|16|\n\n What is the average age? The answer is 'Calculate(Average(Age))'" \
                "DO NOT give anything else other than'Calculate()'."
                )

In [52]:
filepath = "FinQA/dataset/test.json"

with open(filepath) as f:
    data = json.load(f)

programs = []
translated_programs = []
answers = []

for item in tqdm.tqdm(data):
    table_md = convert_to_markdown(item["table_ori"])
    question = item["qa"]["question"]
    
    pre_text = "\n".join(item["pre_text"])
    post_text = "\n".join(item["post_text"])

    programs.append(item["qa"]["program_re"])
    translated_programs.append(translate_expr(item["qa"]["program_re"]))
    answers.append(item["qa"]["answer"])

100%|██████████| 1147/1147 [00:00<00:00, 14709.79it/s]

In [6]:
def get_responses(rank, model_name, data):
    openai.api_key = "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"
    responses = []

    if rank == 0:
        data = tqdm.tqdm(data)
    else:
        data = data

    for item in data:
        table_md = convert_to_markdown(item["table_ori"])
        question = item["qa"]["question"]
        
        pre_text = "\n".join(item["pre_text"])
        post_text = "\n".join(item["post_text"])
        
        context = f"{pre_text}\n\n{table_md}\n\n{post_text}\n\n"
        user_prompt = f"### Context ###\n\n{context}### Question ###\n\n{question}"
        input_prompt = f"### Instruction ###\n\n{system_prompt}\n\n{user_prompt}\n\n### Answer ###\n\n"

        input_ids_length = len(tokenizer.encode(input_prompt)) 
        max_seq_length = 1920 
        while input_ids_length > max_seq_length:
            # truncate the first input_ids_length - max_seq_length tokens
            context = context.split(" ")[input_ids_length - max_seq_length:]
            context = " ".join(context)
            # recreate the input_text
            user_prompt = f"### Context ###\n\n{context}### Question ###\n\n{question}"
            input_prompt = f"### Instruction ###\n\n{system_prompt}\n\n{user_prompt}\n\n### Answer ###\n\n"
            input_ids_length = len(tokenizer.encode(input_prompt)) 


        success = False
        while not success:
            try:
                output = openai.Completion.create(
                                                engine=model_name,
                                                prompt=input_prompt,
                                                temperature=0.1,
                                                max_tokens=128,
                                                top_p=1.0,
                                                stop=["\n\n"]
                                            )
                success = True
            except Exception as e:
                print(e)
                time.sleep(1)
        
        result = output.choices[0].text
        
        responses.append(result)
    
    return responses

In [12]:
responses = get_responses(0, "davinci:ft-columbia-university-2023-05-04-07-51-25", data)

100%|██████████| 1147/1147 [17:23<00:00,  1.10it/s]

In [53]:
gen_programs = []

for response in responses:
    gen_programs.append(extract_answer(response))

In [54]:
# calculate accuracy
prog_correct = 0
exec_correct = 0

wrong_indices = []

for i in range(len(translated_programs)):
    t_prog = translated_programs[i].replace(" ", "")
    g_prog = gen_programs[i].replace(" ", "")

    if t_prog == g_prog:
        prog_correct += 1

    if if_exec_correct(t_prog, g_prog):
        exec_correct += 1
    else:
        wrong_indices.append(i)
        print(i, t_prog, "|", g_prog)

5 (92710000-86842000)/86842000 | (100690000-92710000)/92710000
9 1136-1171 | 1136-1271
15 table_average(netchangefortheyear,none) | (13928+9280+5665)/3
17 (703.1+705.4+2)/2 | (703.1+705.4)/2
18 15.3/(139549/1000) | 15.3/139.5
19 9.7+10.2+(25.0+24.0) | 9.7+10.2
22 (101.88-93.21)/93.21 | (102.93-83.07)/83.07
27 (139549-201808)/201808 | (139.5-201808)/201808
29 3500/3081 | 3081/(15+175+2756)
32 table_max(provisionforincometaxes,none) |
34 61912-367 | 51012-367
35 168-56 | 168+0.3
36 165000/254000 | 254000-165000
37 166000/219000 | 219000-166000
38 4.6+5.5+2 | 1.09+1.11+406
44 (950.4+(957.4+769.1))/3 | (950.4+(957.4+769.1)+3)/2
45 766801*40.85/1000000 | 766.801*40.85/1000000
51 2.3/0.5 | 19.3/0.5
52 5576208*53.8 | 5576208*53.8/100000
53 3/401362 | 401362*3.0/1000000
59 411636+439000 | (411636+439000+556000)/3
63 155+-141+4 | 155-141
70 604.2/8290.6 | 604.2/12067.3
72 1211143/1217121 | 1211143/2171221
75 11.02/9.52/9.52 | (11.02-9.52)/9.52
78 78227+81808 | 78227+81208
79 207.62/97.13 | 207.62-100-(97.13-100)
80 207.62-97.13 | 207.62-100
81 37/1.4 | 29/(1.4/100)
82 102400/15790 | 102.4/15790
84 (1.11+1.08)/1.08 | (1.11-1.08)/1.08
87 2*1000000/2779 | 411636/85/1000000
92 table_average(operatingincome,none) | (895.2+808.4+762.6)/3
93 426932-341003 | 4269322-8349)+345777+(8349+345777
99 7532/180993 | 158578/(158578+40620)
103 (713*42-762*41)/(762*41) | (713-762)/762
105 table_average(endingbalance,none) |
106 945.5/(1.4*1000) | 945.5/(420.5+945.5)
107 (230667-255534)/255534 | (230667-255134)/255134
109 31-30 | 30-4
111 772-8867 | 772-887
114 table_sum(worldwide,none) |
115 367+78 | 469+729
116 table_sum(total,none) |
118 (37.79-31.16)/31.16 | (37.79-24.19)/24.19
120 53818+-36528+157 | 53818-36528
122 327/184/327 | 184/327
123 521.3/655.0 | 655.0/(655.0+521.3)
124 ((208.14-100)/100)**(1/5)-1 | 208.14/100-1
125 102400/619314 | 102300/619314
135 117/579 | 117/144
139 2098*(2098/2014) | 2198/(2198/2)
141 (2.36-2.25)*100 | 2.36/100-2.25/100
143 (9557+6337)/2 |
144 5829+(187+95) | 5735+187+95
150 1336/42546 | 1336/42556
151 100000/100*(138.29-100) | 127.94*(1+(138.29-100))
152 (4-3.9)/4*100 | (3.9-150)/3.9*100
154 1.8*64.2 | 1.8*64.2/1000000)+(1.9*66.64/1000000)+(2.0*64.54/1000000
157 126+111+112 | 112/1178
159 100/3 | 10/3
160 110000000+10000000 | 1939734+10000000
162 12/29 | 29/29000
163 52.25-39.95 | 49.63-35.56
168 table_max(tier2capital,none) |
170 4.9*-1/3.7 | (3.7-3.5)/3.5
172 table_min(cashinstruments,none) |
174 table_sum(otherafrica,none) | 189*1000/189
178 table_sum(distillates,none) |
183 128.16/100 | (128.16-100)/100
185 (180993-118314)/118314 | (180993-118304)/118304
186 44.11-39.03 | (44.11-39.03)/39.03
188 22825000+49250000 | 22825000*(40/100)
189 table_average(operatingprofit,none) |
190 4.7-3.3 | 4.7*1000/1000000
191 11*33.32-13*26.93 | 26.79-33.32
194 20/23 | 162/1187
199 1.074/1.209 | 95/1.209
204 (500.0-240.9)/240.9 | (240.9-257.0)/257.0
206 23000/122300 | 23000/12230
209 (438--291)/291 | (438-291)/291
210 11.8/146.1 | 9.9/146.1
211 342313*113.39/1000000 | 1023202*109.32/1000000
212 8.75/6.91*8.75 | 8.75*(1+65/100)
216 41.9-4.8 | 41.9+27.5+16.1+24.4+4.8+6.3
217 5080/(45708+4800) | 5100/45708
218 18.1-6.3 | 18.1*(1-6.3/100)
219 (2.2-2.7)/2.7 | (2.2-0.0)/0.0
220 table_average(totalassets,none) | (911.51+938.55)/2
223 2.13/100*64.2 | 2.13/100
225 19+12 | 41*(12/100)
227 1.42/(1+25/100) | 13.2/(100-24/100)
230 (378-419)/419 | (419-378)/378
231 (31-24)/24 | (24-31)/31
234 707-48.87 | 707*48.87
236 (687125-650212)/650212 | (687125-652012)/652012
237 126/992 | 126/973
240 760000+857679+898500+960764+1304431 | 760+857679+898500+960765+1304431
243 (5038+(7729+5400))/3 | (5038+(7.7+5400)+3)/2
244 (96.67-100)/100 | (198.27-100)/100
245 109669-112824 | 109669-122824
247 503000/298 | 173000/298
248 24700/101500 | 26900/12230
250 5/4*5 | 5+4
251 2140954/151945 | 2140954/1519704
252 808043/3700106 | 808043/3700006
254 2402/21376 | (23778-21776)/21776
257 43634/94205 | 43634/94210
260 (-5205--1636)/-1636 | (-1636--5205)/-5205
261 (235.63-104.23)/104.23 | (235.63-100)/100-(104.23-100)/100
263 (108.7+138.0+127.1-127.1)/127.1 | 127.1-148.9
264 table_max(provisionforcreditlosses,none) |
265 163000/57800/163000 | 57800/163000
267 574+173 | 574+602+665+729+785
268 table_max(ultimatetrendrate,none) |
270 (107-66)/66 | 66/107
276 21+99 | 99-21
278 19/(63+81) | 19/63
281 384102+121417-(381415+65439) | 384102-381415
283 1220-1214 | 1.2-1.2-1.2
292 (58219-71267)/71267 | (71267-58419)/71267
294 (20500-18100)/18100 | 20500/18100-1
297 (17.7-19.1)/19.1 | (22.3-19.1)/19.1
298 ((73+(104+61))/2+3)/2 | (104+61+73)/3
304 42.5/(61592/1000) | 42.5/61592
313 8/2-1 | 8/2-1/2
315 342.9+78.5 | 342.9+78.5+154.8
316 ((370.32-100)/100)**(1/5)-1 | 370.32/100-1
321 1205260/3063816 | 1205260/3063808
323 (665-1.2*1000)/(1.2*1000) | (665-1202)/1202
324 (100690000-92710000)/92710000 | (566499000-100690000)/100690000
325 318063-60224 | 318063-110457
328 (4.5-4.25)*400.0*1000000 | 77.0/4.25/1000000
330 7327-20963 | 20963-496
332 1328-176 | 1434-176
335 table_average(initialhealthcaretrendrate,none) | (8.25+8.0+4.5)/3
337 (168.4-148.5)/148.5 | (148.5-211.5)/211.5
339 (28.8-30.3)/30.3 | (26.2-28.8)/28.8
343 (177.79-100)**(1/5-1)-1 | (177.79-100)/100
344 265409/268766 | 6271/26876
347 table_sum(vestedduringtheyear,none) | 66299+153644+420500
348 60.6-100/22 | 60675/(22/100)
349 (9981+6788)/93033 | 9981/99033
351 5009/6304 | 5009/6824
356 2327.2/12988.7 | 2327.2/13981.9
357 (46957000-27316000)/27316000 | (469957000-27316000)/27316000
360 17057.4-16772.9 | (17057.4-16772.9)/16772.9
361 2.6/(35/100) | 2.6/(60.8/100)
362 242/(242+177947) | 242/177994
366 (40.51+38.94)/2 | 40.51+38.94
369 100000/100*(118.21-100) | (118.21-100)/100
374 (265+172)/2 | 265+172
379 32.73/(1+6/100) | 32.73*(100/6)
381 665-2239-2239 | (2339-823)/823
383 (473.6-139.8)/473.6 | 252.0/473.6
384 2.9/900.1 | 900.1/2.9
389 8985-11057 | (8985-11057)/11057
391 153258/86080 | 153258/86100
395 table_min(collateralposted,none) |
398 (100-13)/100*2.93 | 2.93/(100/100))*3.77*(28/100
399 750/500*100 | (750+500)/11664
402 63/(63+81) | 81/(63+63)
403 0.6+0.1 | 1.8+0.1+0.1
406 (1.6-2.3)/2.3 | (23000-0.1)/0.1
409 (10558+6426)/23556 | (345+322)/23556
411 70/53-1 | 70-53
412 table_max(foreigncurrencytranslation,none) |
414 4091/14 |
417 5758/7975 | 3321/7975
419 665-2239 | 823-2239
422 57/320 | 57/367
424 table_sum(total,none) |
428 4333146-1837 | 1837+60989
430 46.7-38.9-38.9 | (46.7-38.9)/38.9
434 1589-1141 | 1441-1589
436 3671500/132038 | 132038*27.81
438 33.5/2.5 | (33.5-3)/2.5
441 30+1 | 23-292
442 9.45/(1+23/100) | 7.66*(23/100)
443 1.7*100/7.75 | 7.75*(100/100)*(42/100)*(100/100)
446 100/40 | 3/40
447 (802-711)/802 | 711/802
448 1096*44-941*44 | 1096-941
453 100/10 |
454 29+32+13 | 29+32+13)*1000000/(29+32+13
457 13400/101500 | 16800/12230
459 4630/46780 | 4630/51410
460 5.5/100+70.6/100 | 70.6/100-1.3
461 (800+700+192)/(800+700+300) | 800+700+192
464 100/20 | 20/20
465 (5080-9165)/9165*100 | (5.1-9.2)/9.2
467 4218065*15.52 | 4218165*15.52
468 13+24+49 | 49/100-5/100
470 table_max(derivatives,none) |
471 765/824 | 764/824
472 76.0+(1.3+2)/2 | 76.0+(77.3+2.0)
475 6.22/(1+7/100) |
483 1-5687/6275 | (5687-6275)/6275
485 (1.2-2.2)/1.2 | (-2199--1201)/-1201
486 197/227 | 197/-224
488 897*(50/100) | 50/100
494 74896/5587388 | 74896/5538388
495 45410/179633 | 45410/179663
498 table_max(netderivativeliabilitiesunderbilateralagreements,none) |
499 table_max(netderivativeliabilitiesunderbilateralagreements,none) |
502 (2.2-4.1)/4.1 | 4.1-2.2
503 (195237-177947)/177947 | (195230-195237)/195237
504 64/54 | 54/64
505 2963/23556 | 2963/23566
507 829*(29/100) | 829-480
508 34/3669 | 174/3266
510 911507-938555 | 911.51-938.55
514 1088+1105+945 | 4944-3
515 (161.9-344.6)/344.6 | (162.2-344.6)/344.6
516 5/6.2 | 6.2/1.4
517 174335/(17984+2248) | 174335/17984
518 43.81-100-(74.57-100) | (43.81-100)/100-(74.57-100)/100
519 10000/30000 | 20000/30000
521 123/1676 | 123/1706
523 (434814-382739)/382739 | (434778-382739)/382739
525 (325.1-400.0)/400.0 | 74.9/325.1
528 (11589+(50131+(23596+63003))+4)/2 |
530 (182.87-149.7)/149.7 | (216.19-100)/100
531 10/9 | 10-9
535 102400*74.83 | 124000*74.83/1000000
542 643/8369 | 8369/3758
546 (938555-923225)/923225 | (938555-921225)/921225
548 (104-87)/87 | 87/104
551 563220/3063816 | 563220/3063808
553 3.87/100*(3.87/100/(2.56/100)) | 3.87/100-2.56/100
556 9*1000000/411636 | 60000/411636
560 (272.59-243.79)/243.79 | (272.59-200.32)/200.32
561 15477-6040 | 15477/(15477-6271)
563 390239/777443 | 390224/777443
564 10919/(7*1000) | 799/7.0
569 1211143/1217121 | 1211143/2171221
570 6882/70842 | 678/77274
573 1.8/5.6 | 1.8/11.2
574 table_average(structuredcommercialloanvehicles,none) | (7.2+5.3)/2
576 8.86*3227753 | 2211138*9.25)+(1116615*8.12
578 209/191/191 | (209-191)/191
579 (2.6-2.2)/2.2 | 2.6*1000/2.2
581 (666.9-577.8)/577.8 | (666.9-542.9)/542.9
582 3515/23556 | 1515/23556
588 table_average(liabilities,none) |
590 (6.6+3.7)/426.6 | 6.6/426.6
594 (320-271)/271 | 367+47
596 (385+383+380)/3 | 385+383+380
599 126.6/70.5-1-(214.4/126.6-1) | 126.6-70.5
601 5.8+6.3 | 5.8-6.3
608 (1279337-1019953)/1019953 | (1279337-1010953)/1010953
609 53.8*5576208/1000000 | 2*100000*53.8/1000000
610 9.5*(33/100) | 2+7.3)/(33/100
612 table_average(endofyear,none) |
615 (109.8-1000000)/2616618 | 109.8/2616618
616 (198.05-146.97)/146.97 | (191.27-100)/100
619 table_average(netsales,none) |
620 (222510-200077)/200077 | (222507-200077)/200077
623 635/1000 | 635.9/1000
624 (306222-278395)/278395 | (306222-278439)/278439
626 -4096>891 | 4196>891
627 (7729*(21/100)-5038*(14/100))/(5038*(14/100)) | (7729-5038)/5038*100
628 180+291 | 291>180
633 24/15-1 | (24-15)/15
634 (5829-5735)/5735 | 5829-5735
635 (27885-35066)/35066 | (27895-35106)/35106
636 13.4/14.7 | 8.0/13.4
637 1597+816 | 816+(1714-816)
638 2402/21376 | (23778-21776)/21776
641 (119-86+86)/2 | (119-86)/86
642 177.26-151.16-151.16 | (228.97-151.16)/151.16
644 (80.74-128.16)/128.16 | 80.74-128.16
645 5283.3*(15/100) | 1720.8/(1720.8+2467.1)
646 258.6-250.0-1.4 | 258.6-1.4
651 6900/220600 | 6900/221600
652 150+175+2756 | 20+(756+150+175)
656 (531.8+243.5)/1020.1 | 243.5/1020.1
660 760000*1000*(7.458/100) | 760000*(7.458/100)
662 27/5041 | 27/5.0
664 (30000-20000)/30000 | 20000/30000
666 (29.26-24.57)/24.57 | (29.26-24.19)/24.19
668 1-89/99 | 89/99
670 (500.0-240.9)/240.9 | (240.9-257.0)/257.0
672 2229188*100/2.5 | 2229188*(2.5/100)
673 (313.45-100)/100-(198.18-100)/100 | (313.45-100)/100-(216.54-100)/100
677 (169-138)/138 | (39-57)/57
678 259.5+0.2 | 176.7/617.9
679 78467-75716 | 78467-75706
680 96/581 | 59/581
683 (581-367)/581 | 367/581
687 12300+17000+2800+47800 | 12300+17000+2800
689 158578-118314 | 158578-118304
691 32800/113300 | 32000/113300
695 46984/172095 | 4968/172095
696 (5301-4229)/4229 | (5301-4219)/4219
697 (109669-112824)/112824 | (109669-122824)/122824
698 1171-1701 | 1701-1573
702 465/7170 | 1.6/7170
703 517/476 | 1.079/517
709 19733/61535 | 19733/213520
710 table_average(netunrealizedinvestmentgains,none) |
711 110000/65000 | 110*1000/65*1000
713 (145095+(56616+217692)+3)/2 | (56616+217692+145109)/3
714 932*0.44 | 932/(0.44/100)
716 (9.09-5.15)/5.15 | (9.09-6.79)/6.79
718 1962822/4333146 | 1962822/4332346
720 121.0/268.4 | 41.9/268.4
721 12.0/(19064/1000) | 12.0/19062
725 (30.56+35.61)/2 | 42.96/2.2
726 2690/18988 | 2690/28383
729 table_sum(asphalt,none) | 74+(74+75)
730 480*(27/100) | 480/(27/100)
733 2975-914 | 2975+(2+3+4+5+6+7+8+9+10)
734 (28114-31947)/31947 | (107551-28114)/28114
735 4934+28524 | 28524-4934
738 (240+(228+219))/3 | (279+280+(228+219))/3
741 26466/32339 | 26466/51596
742 4229/7857 | 4219/7857
745 200*1000000*(7.375/100) | 7.375/100*(1+(7.375/100))
750 43.9*1000000 | 5754>5754
755 (86069-88215)/88215 | (86069-8821)/8821
756 4900/14773 | 4900/14775
759 (9.6-8.7)/8.7 | 8.7/9.6
761 50.33*4999 | 49.17*4999
763 table_sum(developmentcostsincurredduringtheperiod,none) |
766 divide(3465,table_sum(total,none)) | 3465/(619+1782+10507+8026)
767 5/100-3/100 | 5/100*(13/100))*(10/100)*(3/100)*(5/100
771 378/1782 | 73/1782
773 511.7/605.5 | 511.7/798.3
778 2180592-51410 | 51410-(4.6*1000)
784 1546-7327 | 20963-496
785 1224-1214 | 1+2+1
789 table_min(effectivetaxrate,none) |
790 2728290/2912456 | (2912456-2728290)/2728290
791 (309183+(217692+145095))/3 | (217692+145100+309130)/3
792 table_average(settlements,none) |
793 (8.8-1.0)/1.0 | (1.0-8.8)/8.8
796 817388/2030900 | 817388/(817388+243331)
797 1084*108.51 | 108.51*1000/1000000
803 (64.8-1000000)/1.11 | 1.11/1.2*1000000
805 420.5/750.0 | 750.0/420.5
806 28114-31947 | 28947-28094
807 29/(29+4)-8/(8+2) | 29/8-(2/66)
810 2408+1364 | 3772/2
814 105/190 | 105/156
815 (236-3057)/3057 | (236-189)/189
816 table_average(expectedvolatility,none) |
817 7/4.7 | 7/6
820 375*(5.0/100) | 5.0/100*375*(2/3)
822 203.87-161.9 | 161.9/100-1
824 table_max(tier1capital,none) |
827 (1135-1016)/1016 | (1135-1106)/1106
833 1000000/100*(311.81-100) | 311.81-100000
834 8945694*40.85/1000000 | 8945694-766801
835 318063+110457-(60224+77901) | 318063+110457+60224
837 85.05-81.99 | 70.18-81.05
838 2435/9475 | 2435/9474
840 2902/14773 | 2902/14733
850 (1135-1016)/1016 | (779-850)/850
852 338501/3540009 | 325.1+59.8
854 210-182 | 182+7
856 156.6/17.3-170.6/21.9 | 17.3/156.6-21.9/170.6
858 38+-110+1 | 63-116
859 (18.1-6.3-(14.6-5.2))/(14.6-5.2) | (18.1-14.6)/14.6
861 136+132+137 | 137-132
862 1432/875 | 11257/7263
863 127.1-70.4 | 70.4+127.1
864 (856240-911507)/911507 | 856240/911507
865 187/5829 | 187/(5829-5735)
868 table_average(netsales,none) |
869 5829-100 | 5829-154
872 10.6+11 | 10.6+11+11.2
876 (16.8-17.7)/17.7 | (19.1-22.3)/22.3
878 7327-20963 | (20963-496)/496
880 (534648-419651)/419651 | (532448-419651)/419651
882 110457/77901 | 121417/93220
884 (217692-145095)/145095-100 | (217692-145109)/145109
887 19.4+19.4+19.4 | 12.9*3
888 217.56>296.67 | 217.56>100
891 1.345*1000+30 | 1.345*(1-30/1000000)
892 table_min(alternativeinvestments,none) |
896 612.5*1000000*(4.72/100) | 4.4/100*(612.5*1000)
897 (1473+4218)/2 | 1473/4218
898 40859/138930 | 4278/40859
902 69.8/(172099/1000) | 69.8/(69.8+466)
904 2793/62.2 | 2793/4423
909 (776-748)/748 | (776-773)/773
911 546.5-516.9 | 546.5-531.6
913 705.4/703.1-1 | (703.1-705.4)/705.4
916 10000000/(110000000+10000000) | 450060/120000000
917 190/289 | 156/289
918 (26.6-47.6)/47.6 | (47.6-26.6)/26.6
921 3.79-3.68-100 | 3.79/100-3.68/100
926 1990/2655 | 199/2655
933 2/14.9 | 16.9-14.9
939 (66/100*28383-40/100*12099)/(40/100*12099) | (12098-28383)/28383
942 265+-557 | 265+172
945 (1983-1667)/1667 | (1988-1667)/1667
948 17.0-18.9 | 26.6-24.8
950 703.1+18.2 | (703.1-705.4)/705.4
951 139549-201808 | 139.5-201808
953 217692/139255 | 217692/14400
954 54/(52+(64+54)+19+16) | 77/(75+77)
958 205500/8800 | 205500/(8/100)
959 table_average(protectcrackspreadvalues,none) |
960 88+4 | 88+83
961 83539/1000/585.3 | 83539/585.3
965 837/5873 | 837/(5873+837)
966 127.1-70.4 | 70.4+127.1
967 203.4+(231.1+203.4)+3 | (231.1+203.4+221.1)/3
972 100000/100*(198.18-100) | 198.18-100000
973 1125734*10.91 | 1257734*10.91
978 253907/3543016 | 59.8/(325.1+59.8)
982 (26643-50079)/50079 | 26643/50079
983 16568/24859 | 16056/24859
986 153644/2330532 | 153644/23305322
987 2.7/(31.2+2.7) | 2.7*1000/31.2
988 table_max(collateralposted,none) |
991 40620+-18205 | 18205+40620
992 1423/59677 | 1838/78975
993 79.0/268.4 | 41.9/268.4
995 1410.5-1229.0-1229.0 | (1410.5-1143.3)/1143.3
996 173000/503000 | (173000+(60-1))/503000
998 (101-114)/114 | (101-100)/100
999 558368-506032 | (558368-506032)/506032
1000 (145.51-100)/100 | (153.24-100)/100
1001 (4425-4277)/4277 | (4427-4919)/4919
1002 (426932-341003)/341003 | 8349/42693
1004 581+123 | 367+(581-367)
1007 160.62/100 | (160.62-100)/100
1010 301-665 | 823--448
1011 table_sum(accumulatedothercomprehensiveloss,none) | 61.1+16.6+6.3
1019 426932-341003 | 772709-426932
1020 997/(7*1000) | 997/(7.0-997)
1021 384102-78841 | 384102-121417
1022 322.6/271.1 | 322.6-100.0
1025 353+6-32 | 353+6+32
1028 3474/19941 | 3543/21813
1030 4.8/212.7 | 102.083/100
1032 60-50 | 50/100-60/100
1034 (377677-388669)/388669 | (377767-388669)/388669
1035 875-848 | 848-1373
1037 (6608-6770)/6770 | (6658-6770)/6770
1039 957.4/1410.5 | 1410.5/1410.5
1042 326.5+328.4+322.4+3 | (322.4+326.5+328.4)/3
1044 9.3-8.4+8.4 | (9.3-8.4)/8.4
1047 509-707-707 | (509-707)/707
1052 (64350-40000)/40000 | (66000-40000)/40000
1053 124/747 | 124/623
1055 (534648-419651)/419651 | (5326-492651)/492651
1059 (8690-7943)/7943 | (8890-7943)/7943
1060 (2440+3237+4127)/(19941+21813+23988) | 2440/23941
1063 433161/15973855 | 248107/1381508
1069 265436-188649 | 265436-186449
1070 159/898 | 303/898
1072 3.5+2.6+3.7 | 3.5+2.6
1079 14-3 | 14--3
1081 1277+-466+-515 | 1277--466
1082 110.17*(1564746-1482914) | 2148914*110.17
1084 (66000-64350)/64350 | (66000-40000)/40000
1088 487-516 | 487-234
1089 175/3081 | 150/3081
1093 170+7819 | 7819-170
1097 2/(8.2-2) | 8.2/2.0
1103 (750+1000)/5700 | 750/5700
1105 (165172-222427)/222427 | 40438/(165172/100)
1107 3063816*4 | 1631816/(89.66/100)
1110 23/2329 | 23/76
1111 (6.91-8.75)/8.75 | (8.75-6.91)/6.91
1114 1.0*1000*(5.0/100) | 50/2
1118 1371/1571 | 1703/19403
1123 (348-259)/259 | (342-301)/301
1124 56-34 | 122-56
1126 3147/5545 | 2321/4244
1129 262+-472+-102 | 262--472
1131 (8.05-6.91)/6.91 | (6.91-8.05)/8.05
1132 3664-3474 | 3474-3474
1133 (750+1000+750)/5700 | 5.7/67
1138 1205260*89.92-1133106*92.59 | 1205260-1133106
1144 (318+-57+11)/3 |
1145 3671500/132038 | 132038/(132038+2094800)
1146 1.5+1.4+1.5 | 1.5*1000*(1.4+1.5)*1000

In [56]:
prog_correct / len(translated_programs)

0.5108979947689625

In [43]:
if_exec_correct("286.61>198.09" , "286.61>198.09")

True

In [41]:
eval("286.61>198.09")

True

In [13]:
# result = {
#     "model": "davinci:ft-columbia-university-2023-05-04-07-51-25",
#     "system_prompt": system_prompt,
#     "responses": responses,
# }


# with open("gpt3-finetune.json", "w") as f:
#     json.dump(result, f, indent=4)